Improve exception handling
messerli-informatik-ag/meta-generator pull request #52
Opened 2020-04-20 13:32 UTC by FreeApophis

2020-04-20 13:37 UTC, FreeApophis commented
Die ersten 3 commits gehören zu PR #48 - ich brauch PR #48 als Basis für FormatException.

Also PR #48 zuerst mergen.

2020-04-20 14:10 UTC, FreeApophis commented
Beispiel aus Bug #32 

Exception in module: MetaGeneratorProjectPlugin
Expecting Messerli.VsSolution.Token.EndProjectToken but got Project at Line 43 Column 1.

2020-04-21 05:29 UTC, dngroth submitted a review, later dismissed

2020-04-22 09:51 UTC, janhohenheim requested changes

2020-04-22 09:51 UTC, jnferner commented on VsSolution/Parser/SolutionParser.cs
> +            var tokenizer = new Tokenizer(lexerRules, s => new LexerReader(s), l => new LinePositionCalculator(l));
The number of parameters is starting to warrant explicit parameter identifiers.

2020-04-22 09:51 UTC, jnferner commented on MetaGenerator/ExceptionFormatter.cs
> +                if (_globalOptions.Verbose && exception.StackTrace is { })
remove (slight) code duplication by binding `exception.StackTrace` to a variable like so: `exception.StackTrace is { } stackTrace`

2020-04-22 09:51 UTC, jnferner commented on MetaGenerator/ExceptionFormatter.cs
> +            if (exception is AggregateException aggregateException)
Move the positive and negative branches into own functions.

2020-04-22 11:50 UTC, janhohenheim approved these changes

2020-04-22 15:23 UTC, merged